# use 'esphome window_blind_gym.yaml compile' to build.
substitutions:
  device_name: breadboard-fan
  friendly_name: Breadboard Test Fan
  node_name: breadboard_fan
  # wifi_static_ip: !secret wifi_static_ip_breadboard_fan


packages:
  # Board specific packages
  main: !include packages/fan_4_pin.yaml
    
  # Boilerplate packages
  wifi: !include packages/wifi_dhcp.yaml
  ota: !include packages/ota.yaml
  uptime_sensor: !include packages/uptime_sensor.yaml

logger:
  level: VERBOSE
  logs:
    dht: DEBUG