# use 'esphome window_blind_dining.yaml compile' to build.
substitutions:
  device_name: front-door-ble-presence
  friendly_name: Front Door Bluetooth LE Presence Detector
  node_name: front_door_ble_presence
  wifi_static_ip: !secret wifi_static_ip_front_door_ble_tracker
  
packages:
  # Board specific packages
  board: !include packages/board_esp32_az_delivery_devkit_v4.yaml

  # Boilerplate packages
  wifi: !include packages/wifi_static_ip.yaml
  ota: !include packages/ota.yaml
  uptime_sensor: !include packages/uptime_sensor.yaml

# Let home assistant find the device
api:

# Enable the esp32 ble support
esp32_ble_tracker:

binary_sensor:
  # Presence based on MAC address
  - platform: ble_presence
    mac_address: 70:B9:50:D3:9C:45
    name: "ESP32 BLE Tracker Tesla"
    # min_rssi: -80dB


  # Presence based on MAC address
  - platform: ble_presence
    mac_address: B0:99:D7:BD:C1:B1
    name: "ESP32 BLE Tracker Samsung TV"
    # min_rssi: -80dB

logger:
  level: INFO