# this configuration file has all empty custom stepper set up.
# use 'esphome tmc5160_test.yaml compile' to build.
substitutions:
  device_name: office-window-blind
  friendly_name: Office Window Blind
  node_name: office_window_blind
  wifi_static_ip: !secret wifi_static_ip_office_window_blind
  closed_position: '4400'
  opening_clutch_backlash_adjustment: '0'

  platform: ESP8266
  board: d1_mini
  SPI_CLK_PIN: GPIO14
  SPI_MOSI_PIN: GPIO13
  SPI_MISO_PIN: GPIO12
  TMC_CS_PIN: GPIO15
  TMC_SLEEP_PIN: GPIO04
  TMC_RESET_PIN: GPIO05

  # platform: ESP32
  # board: d1_mini
  # SPI_CLK_PIN: GPIO18
  # SPI_MOSI_PIN: GPIO23
  # SPI_MISO_PIN: GPIO19
  # TMC_CS_PIN: GPIO5
  # TMC_SLEEP_PIN: GPIO14
  # TMC_RESET_PIN: GPIO16
  
  # Can't reference secrets from YAML's in the packages folder, so use substitutions instead
  # This can be swapped to the parameterised !include syntax
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_gateway: !secret wifi_gateway
  wifi_dns: !secret wifi_dns
  ota_password: !secret ota_password

packages:
  wifi: !include packages/wifi_static_ip.yaml
  ota: !include packages/ota.yaml
  roller_blind: !include packages/roller_blind.yaml
  uptime_sensor: !include packages/uptime_sensor.yaml

logger:
  level: VERBOSE