defaults:
  motor_id: tmc_stepper
  motor_current_resistor: 0.075ohm
  motor_motor_current: 1.68A
  motor_motor_hold_power: 30%
  motor_max_speed: '500'
  motor_acceleration: '200'
  motor_deceleration: '200'
  motor_direction: normal # or reversed
  disable_driver_on_stop: 'True'

  SPI_CLK_PIN: GPIO14
  SPI_MOSI_PIN: GPIO13
  SPI_MISO_PIN: GPIO12
  
  TMC_CS_PIN: GPIO15
  TMC_SLEEP_PIN: GPIO04
  TMC_RESET_PIN: GPIO05

esphome:
  libraries:
    # Libraries from PlatformIO
    - SPI
    - tommag/TMC5160 # Requires SPI, must be before this in the list
  on_boot:
    then:
      - script.execute: 
          id: set_speed
          speed: !lambda "return id(saved_speed);"
      - script.execute: 
          id: set_acceleration
          acceleration: !lambda "return id(saved_acceleration);"
      - script.execute: 
          id: set_deceleration
          deceleration: !lambda "return id(saved_deceleration);"

globals:
  - id: saved_speed
    type: float
    initial_value: ${motor_max_speed}
    restore_value: true
  - id: saved_acceleration
    type: float
    initial_value: ${motor_acceleration}
    restore_value: true
  - id: saved_deceleration
    type: float
    initial_value: ${motor_deceleration}
    restore_value: true

script:
  - id: set_speed
    parameters:
      speed: int
    then:
      - lambda: "id(${motor_id}).set_max_speed(speed);"
      - globals.set:
          id: saved_speed
          value: !lambda "return speed;"
      - sensor.template.publish:
          id: ${node_name}_max_speed
          state: !lambda return speed; 

  - id: set_acceleration
    parameters:
      acceleration: int
    then:
      - lambda: "id(${motor_id}).set_acceleration(acceleration);"
      - globals.set:
          id: saved_acceleration
          value: !lambda "return acceleration;"
      - sensor.template.publish:
          id: ${node_name}_acceleration
          state: !lambda return acceleration; 

  - id: set_deceleration
    parameters:
      deceleration: int
    then:
      - lambda: "id(${motor_id}).set_deceleration(deceleration);"
      - globals.set:
          id: saved_deceleration
          value: !lambda "return deceleration;"
      - sensor.template.publish:
          id: ${node_name}_deceleration
          state: !lambda return deceleration; 

spi:
  clk_pin: ${SPI_CLK_PIN}
  mosi_pin: ${SPI_MOSI_PIN}
  miso_pin: ${SPI_MISO_PIN}
  
stepper:
  - platform: tmc5160
    id: ${motor_id}
    
    cs_pin: ${TMC_CS_PIN}
    sleep_pin: ${TMC_SLEEP_PIN}
    reset_pin: ${TMC_RESET_PIN}

    current_resistor: ${motor_current_resistor}
    motor_current: ${motor_motor_current}
    motor_hold_power: ${motor_motor_hold_power}
    max_speed: ${motor_max_speed}
    acceleration: ${motor_acceleration}
    deceleration: ${motor_deceleration}
    direction: ${motor_direction}
    disable_driver_on_stop: ${disable_driver_on_stop}

api:
  actions:
    - action: set_speed
      variables:
        speed: int
      then:
        - script.execute:
            id: set_speed
            speed: !lambda "return (float)speed;"

    - action: set_acceleration
      variables:
        acceleration: int
      then:
        - script.execute:
            id: set_acceleration
            acceleration: !lambda "return (float)acceleration;"

    - action: set_deceleration
      variables:
        deceleration: int
      then:
        - script.execute:
            id: set_deceleration
            deceleration: !lambda "return (float)deceleration;"


sensor:
  - platform: template
    id: ${node_name}_max_speed
    name: ${friendly_name} Max Speed
    lambda: return (int)id(${motor_id}).get_max_speed();
    update_interval: never
    
  - platform: template
    id: ${node_name}_acceleration
    name: ${friendly_name} Acceleration
    lambda: return (int)id(${motor_id}).get_acceleration();
    update_interval: never
    
  - platform: template
    id: ${node_name}_deceleration
    name: ${friendly_name} Deceleration
    lambda: return (int)id(${motor_id}).get_deceleration();
    update_interval: never
    